from typing import TypedDict, List, Dict, Any


class AgentState(TypedDict):
    # Original request from the user
    user_input: str

    # Current action selected by the planner
    plan: List[str]

    # Arguments generated by Ollama for the current tool
    tool_arguments: Dict[str, Any]

    # Current action being executed
    current_step: int

    # Maximum number of agent steps allowed
    max_steps: int

    # Results returned by tools
    tool_results: List[Dict[str, Any]]

    # History of the agent's decisions
    reasoning_history: List[Dict[str, Any]]

    # Error information
    error: str

    # Final answer
    final_response: str